package com.api.JsonPlaceHolderCases.Users;

import com.api.base.ApiHelper;
import io.restassured.response.Response;
import org.json.JSONObject;
import org.testng.annotations.Test;

import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;

public class Test05 extends ApiHelper{


    @Test
    public void testUpdateUsers()  {
        String id="1";

        JSONObject body = new JSONObject();
        body.put("name", "shashank");
        body.put("username", "srivastava");
        body.put("email", "Sincere@april.biz");

        JSONObject geo = new JSONObject();
        geo.put("lat", "-37.3159");
        geo.put("lng", "81.1496");

        JSONObject address = new JSONObject();
        address.put("street", "Kulas Light");
        address.put("suite", "Apt. 556");
        address.put("city", "Gwenborough");
        address.put("zipcode", "92998-3874");
        address.put("phone", "1-770-736-8031 x56442");
        address.put("geo", geo);

        JSONObject company = new JSONObject();
        company.put("name", "Romaguera-Crona");
        company.put("catchPhrase", "Multi-layered client-server neural-net");
        company.put("bs", "harness real-time e-markets");

        body.put("address", address);
        body.put("company", company);

        Response response = ApiHelper.sendPutRequest("/users/"+id, String.valueOf(body));
        String responseBody = response.getBody().asString();

        System.out.println(responseBody);


        response.then()
                .statusCode(200) // Assert that the status code is 201 (Created)
                .body("id", notNullValue()) // Assert that the id is present (generated by the server)
                .body("name", equalTo("shashank")) // Assert that the name is correct
                .body("username", equalTo("srivastava")) // Assert that the email is correct
                .body("address.city", equalTo("Gwenborough")) // Assert that the city in the address is correct
                .body("company.name", equalTo("Romaguera-Crona")); // Assert that the company name is correct

    }
}